package com.smanis.coffee.forms;

import com.smanis.coffee.AppPreferences;
import com.smanis.coffee.models.BeanModel;
import com.smanis.coffee.models.NonEditableTableModel;
import com.smanis.coffee.service.DataService;
import com.smanis.coffee.service.TableService;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.JRootPane;
import javax.swing.KeyStroke;

/**
 * @author semanis
 */
public class BeanUtilization extends javax.swing.JDialog {

    /**
     * Creates new form BeanUtilitzation
     */
    public BeanUtilization(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        initOther();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        labelBean = new javax.swing.JLabel();
        buttonExit = new javax.swing.JButton();
        textBeanName = new javax.swing.JTextField();
        labelPurchased = new javax.swing.JLabel();
        labelRoasted = new javax.swing.JLabel();
        labelRemaining = new javax.swing.JLabel();
        textPurchased = new javax.swing.JTextField();
        textRoasted = new javax.swing.JTextField();
        textRemaining = new javax.swing.JTextField();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Bean Utilization");
        setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        setMaximumSize(new java.awt.Dimension(504, 303));
        setMinimumSize(new java.awt.Dimension(504, 303));
        setName("dialogBeanUtilization"); // NOI18N
        setPreferredSize(new java.awt.Dimension(504, 303));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        labelBean.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        labelBean.setText("Bean:");

        buttonExit.setMnemonic('x');
        buttonExit.setText("Exit");
        buttonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExitActionPerformed(evt);
            }
        });

        textBeanName.setEditable(false);
        textBeanName.setFocusable(false);

        labelPurchased.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        labelPurchased.setText("Purchased:");
        labelPurchased.setMaximumSize(new java.awt.Dimension(103, 32));
        labelPurchased.setMinimumSize(new java.awt.Dimension(103, 32));
        labelPurchased.setPreferredSize(new java.awt.Dimension(103, 32));

        labelRoasted.setText("Roasted:");

        labelRemaining.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        labelRemaining.setText("Remaining:");

        textPurchased.setEditable(false);
        textPurchased.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        textPurchased.setFocusable(false);
        textPurchased.setMaximumSize(new java.awt.Dimension(102, 32));
        textPurchased.setMinimumSize(new java.awt.Dimension(102, 32));
        textPurchased.setPreferredSize(new java.awt.Dimension(102, 32));

        textRoasted.setEditable(false);
        textRoasted.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        textRoasted.setFocusable(false);
        textRoasted.setMaximumSize(new java.awt.Dimension(102, 32));
        textRoasted.setMinimumSize(new java.awt.Dimension(102, 32));
        textRoasted.setPreferredSize(new java.awt.Dimension(102, 32));

        textRemaining.setEditable(false);
        textRemaining.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        textRemaining.setFocusable(false);
        textRemaining.setMaximumSize(new java.awt.Dimension(102, 32));
        textRemaining.setMinimumSize(new java.awt.Dimension(102, 32));
        textRemaining.setPreferredSize(new java.awt.Dimension(102, 32));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelBean, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(textBeanName, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 9, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelPurchased, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelRoasted, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelRemaining, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textRoasted, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                    .addComponent(textPurchased, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textRemaining, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonExit)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(labelBean)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textBeanName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPurchased, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textPurchased, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelRoasted)
                    .addComponent(textRoasted, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textRemaining, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelRemaining))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonExit)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(514, 333));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        System.out.println("form Closing!");
        this.exitForm();
    }//GEN-LAST:event_formWindowClosing

    private void buttonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExitActionPerformed
        this.exitForm();
    }//GEN-LAST:event_buttonExitActionPerformed

    public void setBeanModel(BeanModel model) {
        this.beanModel = model;

        this.textBeanName.setText(this.beanModel.getBeanName());

    }

    public void setRoastLogModel(NonEditableTableModel model) {
        this.roastLogModel = model;
        this.calculateBeanUtilization();
    }

    /**
     * Calculates Bean utilization for the specified BeanModel and
     * RoastLogModel.
     */
    public void calculateBeanUtilization() {
        int roastCount = this.roastLogModel.getRowCount();
        int columnIndex = TableService.getInstance().getColumnIndex("RoastLog", "Green Weight");

        float gramsUtilized = 0.0f;
        float gramsPerPound = 453.592f;

        for (int i = 0; i < roastCount; i++) {
            gramsUtilized += Float.valueOf((String) this.roastLogModel.getValueAt(i, columnIndex));
        }

        ResultSet rs = null;

        try {
            rs = DataService.getInstance().getBeanById(this.beanModel.getBeanId());
            if (rs != null && rs.next()) {
                float poundsPurchased = rs.getFloat("WeightInPounds");
                float poundsRoasted = gramsUtilized / gramsPerPound;
                float poundsRemaining = poundsPurchased - poundsRoasted;
                poundsRemaining = poundsRemaining < 0.0f ? 0.0f : poundsRemaining;


                this.textPurchased.setText(String.format("%2.2f lbs   (%.2f g)", poundsPurchased, poundsPurchased * gramsPerPound));
                this.textRoasted.setText(String.format("%2.2f lbs   (%.2f g)", poundsRoasted, poundsRoasted * gramsPerPound));
                this.textRemaining.setText(String.format("%2.2f lbs   (%.2f g)", poundsRemaining, poundsRemaining * gramsPerPound));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }

    }

    //------[ private ]--------------------------------------------------------
    private void initOther() {
        // Register an action listener on the Escape key which performs a click of the Exit button.
        ActionListener actionListener = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent actionEvent) {
                exitForm();
            }
        };

        KeyStroke stroke = KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0);

        JRootPane jrp = this.getRootPane();
        jrp.registerKeyboardAction(actionListener, stroke, JComponent.WHEN_IN_FOCUSED_WINDOW);

        // Load up the window preferences, which restores the size/location of the window.
        AppPreferences.loadWindowPreferences(this);
        
    }

    private void exitForm() {
        AppPreferences.saveWindowPreferences(this);

        this.setVisible(false);
    }

    private BeanModel beanModel;
    private NonEditableTableModel roastLogModel;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonExit;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel labelBean;
    private javax.swing.JLabel labelPurchased;
    private javax.swing.JLabel labelRemaining;
    private javax.swing.JLabel labelRoasted;
    private javax.swing.JTextField textBeanName;
    private javax.swing.JTextField textPurchased;
    private javax.swing.JTextField textRemaining;
    private javax.swing.JTextField textRoasted;
    // End of variables declaration//GEN-END:variables
}
