/*
 */
package com.smanis.coffee.forms;

import com.smanis.coffee.AppPreferences;
import com.smanis.coffee.models.NonEditableTableModel;
import com.smanis.coffee.service.TableService;
import com.smanis.coffee.Utility;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.JRootPane;
import javax.swing.JTable;
import javax.swing.KeyStroke;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author semanis
 */
public class CoffeeFrame extends javax.swing.JFrame {

    /**
     * Creates new form CoffeeFrame
     */
    public CoffeeFrame() {
        initComponents();
        initOther();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        tabbedPanel = new javax.swing.JTabbedPane();
        panelRoastLogs = new javax.swing.JPanel();
        panelNotes = new javax.swing.JPanel();
        labelRoastNotes = new javax.swing.JLabel();
        labelTastingNotes = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        textRoastNotes = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        textTastingNotes = new javax.swing.JTextArea();
        panelRoastTable = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableRoasts = new javax.swing.JTable();
        panelContainer = new javax.swing.JPanel();
        panelFilter = new javax.swing.JPanel();
        labelFilter = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        panelButtons = new javax.swing.JPanel();
        btnAddRoastLog = new javax.swing.JButton();
        btnEditRoastLog = new javax.swing.JButton();
        btnDeleteRoastLog = new javax.swing.JButton();
        panelBeans = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        panelPurchases = new javax.swing.JPanel();
        buttonExit = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuItemExit = new javax.swing.JMenuItem();
        menuView = new javax.swing.JMenu();
        menuLookAndFeel = new javax.swing.JMenu();
        menuItemGtk = new javax.swing.JMenuItem();
        menuItemMetal = new javax.swing.JMenuItem();
        menuItemMotif = new javax.swing.JMenuItem();
        menuItemNimbus = new javax.swing.JMenuItem();
        menuItemWindows = new javax.swing.JMenuItem();
        menuItemWindowsClassic = new javax.swing.JMenuItem();
        menuHellp = new javax.swing.JMenu();
        menuItemAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Coffee Roasting Log");
        setName("roastLogs"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridBagLayout());

        panelRoastLogs.setLayout(new java.awt.GridBagLayout());

        panelNotes.setBorder(javax.swing.BorderFactory.createTitledBorder(" Notes "));
        panelNotes.setLayout(new java.awt.GridBagLayout());

        labelRoastNotes.setText("Roasting");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        panelNotes.add(labelRoastNotes, gridBagConstraints);

        labelTastingNotes.setText("Tasting");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        panelNotes.add(labelTastingNotes, gridBagConstraints);

        textRoastNotes.setEditable(false);
        textRoastNotes.setColumns(20);
        textRoastNotes.setRows(5);
        jScrollPane2.setViewportView(textRoastNotes);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 0);
        panelNotes.add(jScrollPane2, gridBagConstraints);

        textTastingNotes.setEditable(false);
        textTastingNotes.setColumns(20);
        textTastingNotes.setRows(5);
        jScrollPane3.setViewportView(textTastingNotes);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 10);
        panelNotes.add(jScrollPane3, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 10, 10);
        panelRoastLogs.add(panelNotes, gridBagConstraints);

        panelRoastTable.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelRoastTable.setLayout(new java.awt.GridBagLayout());

        jScrollPane1.setViewportBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane1.setAutoscrolls(true);

        tableRoasts.setAutoCreateRowSorter(true);
        tableRoasts.setModel(TableService.getInstance().getTableModelRoastLogs());
        tableRoasts.setName(""); // NOI18N
        tableRoasts.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tableRoasts.setShowGrid(true);
        tableRoasts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClick(evt);
            }
        });
        tableRoasts.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tableRoastsKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tableRoasts);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 10);
        panelRoastTable.add(jScrollPane1, gridBagConstraints);

        panelContainer.setLayout(new java.awt.GridBagLayout());

        panelFilter.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        labelFilter.setText("Filter");
        panelFilter.add(labelFilter);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bean Name", "Roast Date" }));
        jComboBox1.setPreferredSize(new java.awt.Dimension(175, 31));
        panelFilter.add(jComboBox1);

        jTextField1.setPreferredSize(new java.awt.Dimension(124, 26));
        panelFilter.add(jTextField1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        panelContainer.add(panelFilter, gridBagConstraints);

        panelButtons.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        btnAddRoastLog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/smanis/coffee/assets/addSmall.png"))); // NOI18N
        btnAddRoastLog.setMnemonic('a');
        btnAddRoastLog.setText("Add");
        btnAddRoastLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddRoastLogActionPerformed(evt);
            }
        });
        panelButtons.add(btnAddRoastLog);

        btnEditRoastLog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/smanis/coffee/assets/editSmall.png"))); // NOI18N
        btnEditRoastLog.setMnemonic('e');
        btnEditRoastLog.setText("Edit");
        btnEditRoastLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditRoastLogActionPerformed(evt);
            }
        });
        panelButtons.add(btnEditRoastLog);

        btnDeleteRoastLog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/smanis/coffee/assets/deleteSmall.png"))); // NOI18N
        btnDeleteRoastLog.setMnemonic('d');
        btnDeleteRoastLog.setText("Delete");
        btnDeleteRoastLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteRoastLogActionPerformed(evt);
            }
        });
        panelButtons.add(btnDeleteRoastLog);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 1.0;
        panelContainer.add(panelButtons, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelRoastTable.add(panelContainer, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.5;
        panelRoastLogs.add(panelRoastTable, gridBagConstraints);

        tabbedPanel.addTab(" Roast Logs ", panelRoastLogs);

        panelBeans.setLayout(new java.awt.GridBagLayout());

        jTable1.setModel(TableService.getInstance().getTableModelBeans());
        jScrollPane4.setViewportView(jTable1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        panelBeans.add(jScrollPane4, gridBagConstraints);

        tabbedPanel.addTab(" Beans ", panelBeans);
        tabbedPanel.addTab(" Bean Purchases ", panelPurchases);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(tabbedPanel, gridBagConstraints);

        buttonExit.setMnemonic('x');
        buttonExit.setText("Exit");
        buttonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExitActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(buttonExit, gridBagConstraints);

        menuFile.setMnemonic('f');
        menuFile.setText("File");
        menuFile.add(jSeparator1);

        menuItemExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/smanis/coffee/assets/exitSmall.png"))); // NOI18N
        menuItemExit.setText("Exit");
        menuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemExitActionPerformed(evt);
            }
        });
        menuFile.add(menuItemExit);

        menuBar.add(menuFile);

        menuView.setMnemonic('v');
        menuView.setText("View");

        menuLookAndFeel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/smanis/coffee/assets/glasses.png"))); // NOI18N
        menuLookAndFeel.setMnemonic('L');
        menuLookAndFeel.setText("Look And Feel");

        menuItemGtk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/smanis/coffee/assets/tux.png"))); // NOI18N
        menuItemGtk.setText("GTK");
        menuItemGtk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemGtkActionPerformed(evt);
            }
        });
        menuLookAndFeel.add(menuItemGtk);

        menuItemMetal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/smanis/coffee/assets/anvil.png"))); // NOI18N
        menuItemMetal.setText("Metal");
        menuItemMetal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemMetalActionPerformed(evt);
            }
        });
        menuLookAndFeel.add(menuItemMetal);

        menuItemMotif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/smanis/coffee/assets/motif.png"))); // NOI18N
        menuItemMotif.setText("Motif");
        menuItemMotif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemMotifActionPerformed(evt);
            }
        });
        menuLookAndFeel.add(menuItemMotif);

        menuItemNimbus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/smanis/coffee/assets/nimbus.png"))); // NOI18N
        menuItemNimbus.setText("Nimbus");
        menuItemNimbus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemNimbusActionPerformed(evt);
            }
        });
        menuLookAndFeel.add(menuItemNimbus);

        menuItemWindows.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/smanis/coffee/assets/windows.png"))); // NOI18N
        menuItemWindows.setText("Windows");
        menuItemWindows.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemWindowsActionPerformed(evt);
            }
        });
        menuLookAndFeel.add(menuItemWindows);

        menuItemWindowsClassic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/smanis/coffee/assets/windowsClassic.png"))); // NOI18N
        menuItemWindowsClassic.setText("Windows Classic");
        menuItemWindowsClassic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemWindowsClassicActionPerformed(evt);
            }
        });
        menuLookAndFeel.add(menuItemWindowsClassic);

        menuView.add(menuLookAndFeel);

        menuBar.add(menuView);

        menuHellp.setMnemonic('h');
        menuHellp.setText("Help");

        menuItemAbout.setText("About...");
        menuItemAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAboutActionPerformed(evt);
            }
        });
        menuHellp.add(menuItemAbout);

        menuBar.add(menuHellp);

        setJMenuBar(menuBar);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExitActionPerformed
        this.exitForm(null);
    }//GEN-LAST:event_buttonExitActionPerformed

    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        AppPreferences.saveWindowPreferences(this);
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void tableMouseClick(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClick
        int row = this.tableRoasts.rowAtPoint(evt.getPoint());
        NonEditableTableModel model = (NonEditableTableModel) this.tableRoasts.getModel();

        // on double-click of a row,  open the editing dialog.
        if (evt.getClickCount() == 2) {
            this.editRoastLog(model, row);
        } else {
            // refresh roast notes/tasting nodes based on the clicked row.
            this.populateNotes(model, row);
        }

    }//GEN-LAST:event_tableMouseClick

    private void menuItemGtkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemGtkActionPerformed
        Utility.setLookAndFeel("gtk", this);

    }//GEN-LAST:event_menuItemGtkActionPerformed

    private void menuItemMotifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemMotifActionPerformed
        Utility.setLookAndFeel("motif", this);
    }//GEN-LAST:event_menuItemMotifActionPerformed

    private void menuItemWindowsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemWindowsActionPerformed
        Utility.setLookAndFeel("windows", this);

    }//GEN-LAST:event_menuItemWindowsActionPerformed

    private void menuItemMetalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemMetalActionPerformed
        Utility.setLookAndFeel("metal", this);

    }//GEN-LAST:event_menuItemMetalActionPerformed

    private void menuItemNimbusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemNimbusActionPerformed
        Utility.setLookAndFeel("nimbus", this);
    }//GEN-LAST:event_menuItemNimbusActionPerformed

    private void menuItemWindowsClassicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemWindowsClassicActionPerformed
        Utility.setLookAndFeel("windowsclassic", this);
    }//GEN-LAST:event_menuItemWindowsClassicActionPerformed

    private void btnEditRoastLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditRoastLogActionPerformed
        int selectedRow = this.tableRoasts.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a Roast Log to edit.");
            return;
        }

        NonEditableTableModel model = (NonEditableTableModel) this.tableRoasts.getModel();
        String roastLogId = (String) model.getValueAt(selectedRow, 0);
        RoastLogEdit rle = new com.smanis.coffee.forms.RoastLogEdit(this, true);
        rle.setRoastLogId(roastLogId);
        rle.setVisible(true);

        if (rle.wasPersisted == true) {
            //this.tableRoasts.setModel(TableService.getInstance().getTableModelRoastLogs());

        }
    }//GEN-LAST:event_btnEditRoastLogActionPerformed

    private void btnAddRoastLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddRoastLogActionPerformed
        RoastLogEdit rle = new com.smanis.coffee.forms.RoastLogEdit(this, true);
        rle.setVisible(true);

        if (rle.wasPersisted == true) {
            //this.tableRoasts.setModel(TableService.getInstance().getTableModelRoastLogs());
        }
    }//GEN-LAST:event_btnAddRoastLogActionPerformed

    private void btnDeleteRoastLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteRoastLogActionPerformed
        int selectedRow = this.tableRoasts.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a Roast Log to delete.");
            return;
        }

        NonEditableTableModel model = (NonEditableTableModel) this.tableRoasts.getModel();
        String roastLogId = (String) model.getValueAt(selectedRow, 0);

        if (JOptionPane.showConfirmDialog(this, "Delete Roast Log?", "Confirm Delete", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.CANCEL_OPTION) {
            return;
        }

        //TableService.deleteRoastLog();

    }//GEN-LAST:event_btnDeleteRoastLogActionPerformed

    private void menuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemExitActionPerformed
        this.exitForm(null);
    }//GEN-LAST:event_menuItemExitActionPerformed

    private void tableRoastsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tableRoastsKeyReleased
        int currentRow = this.tableRoasts.getSelectedRow();
        this.populateNotes((NonEditableTableModel)this.tableRoasts.getModel(), currentRow);
    }//GEN-LAST:event_tableRoastsKeyReleased

    private void menuItemAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAboutActionPerformed
        new AboutDialog(this, true).setVisible(true);
    }//GEN-LAST:event_menuItemAboutActionPerformed

    private void editRoastLog(NonEditableTableModel model, int tableRow) {
        String roastLogId = (String) model.getValueAt(tableRow, 0);

        RoastLogEdit rle = new com.smanis.coffee.forms.RoastLogEdit(this, true);
        rle.setRoastLogId(roastLogId); // set the roast log Id to be edited.
        rle.setVisible(true);
    }

    private void populateNotes(NonEditableTableModel model, int tableRow) {
        // refresh roast notes/tasting nodes based on the clicked row.
        this.textRoastNotes.setText((String) model.getValueAt(tableRow, 13));
        this.textTastingNotes.setText((String) model.getValueAt(tableRow, 14));
    }

    private void initOther() {
        try {
            TableService.getInstance().setupTableRoastLog(this.tableRoasts, this.textRoastNotes, this.textTastingNotes);
            TableService.getInstance().hideColumnsRoastLog(this.tableRoasts);
            TableService.getInstance().setColumnWidthsRoastLog(this.tableRoasts);

            //this.tableRoasts.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
            this.tableRoasts.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
            this.tableRoasts.setIntercellSpacing(new Dimension(10, 10));
            this.tableRoasts.setRowHeight(40);
            // auto-select the first row.
            this.tableRoasts.setRowSelectionInterval(0, 0);

            TableModel model = this.tableRoasts.getModel();
            this.textRoastNotes.setText((String) model.getValueAt(0, 13));
            this.textTastingNotes.setText((String) model.getValueAt(0, 14));

            AppPreferences.loadWindowPreferences(this);

            JRootPane jrp = this.getRootPane();

            // "ENTER" at any time activates the default button.
            // jrp.setDefaultButton(this.buttonExit);
            // register an action listener on the Escape key which performs a click
            // of the Exit button.
            ActionListener actionListener = new ActionListener() {
                public void actionPerformed(ActionEvent actionEvent) {
                    int response = JOptionPane.showConfirmDialog(CoffeeFrame.this, "Exit?", "Confirm Exit", JOptionPane.OK_CANCEL_OPTION);
                    if (response == JOptionPane.OK_OPTION) {
                        buttonExit.doClick();
                    }
                }
            };

            KeyStroke stroke = KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0);
            jrp.registerKeyboardAction(actionListener, stroke, JComponent.WHEN_IN_FOCUSED_WINDOW);

        } catch (Exception e) {
            System.out.println("initOther! " + e.getMessage() + " " + " " + e.getClass());
        }
        
        this.tableRoasts.requestFocus();
    }

    public boolean shouldExit = false;

    //protected DefaultTableModel tableModel = new DefaultTableModel();

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddRoastLog;
    private javax.swing.JButton btnDeleteRoastLog;
    private javax.swing.JButton btnEditRoastLog;
    private javax.swing.JButton buttonExit;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel labelFilter;
    private javax.swing.JLabel labelRoastNotes;
    private javax.swing.JLabel labelTastingNotes;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenu menuHellp;
    private javax.swing.JMenuItem menuItemAbout;
    private javax.swing.JMenuItem menuItemExit;
    private javax.swing.JMenuItem menuItemGtk;
    private javax.swing.JMenuItem menuItemMetal;
    private javax.swing.JMenuItem menuItemMotif;
    private javax.swing.JMenuItem menuItemNimbus;
    private javax.swing.JMenuItem menuItemWindows;
    private javax.swing.JMenuItem menuItemWindowsClassic;
    private javax.swing.JMenu menuLookAndFeel;
    private javax.swing.JMenu menuView;
    private javax.swing.JPanel panelBeans;
    private javax.swing.JPanel panelButtons;
    private javax.swing.JPanel panelContainer;
    private javax.swing.JPanel panelFilter;
    private javax.swing.JPanel panelNotes;
    private javax.swing.JPanel panelPurchases;
    private javax.swing.JPanel panelRoastLogs;
    private javax.swing.JPanel panelRoastTable;
    private javax.swing.JTabbedPane tabbedPanel;
    private javax.swing.JTable tableRoasts;
    private javax.swing.JTextArea textRoastNotes;
    private javax.swing.JTextArea textTastingNotes;
    // End of variables declaration//GEN-END:variables
}
